-- SupabaseZombi 전용 테이블 생성 SQL 및 권한 설정
-- Supabase SQL Editor에서 실행하여 초기 테이블을 생성하고 필요한 권한을 부여하세요.

-- 1. 테이블 생성 (기본 테이블 이름: "keep-alive")
CREATE TABLE IF NOT EXISTS "keep-alive" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 테이블 권한 부여 (anon, authenticated 역할 대상)
GRANT SELECT, INSERT, DELETE ON TABLE "keep-alive" TO anon, authenticated;

-- 3. Row Level Security (RLS) 설정 (선택 사항: RLS 사용 시)
ALTER TABLE "keep-alive" ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 (중복 생성 방지)
DROP POLICY IF EXISTS "Allow keepalive select" ON "keep-alive";
DROP POLICY IF EXISTS "Allow keepalive insert" ON "keep-alive";
DROP POLICY IF EXISTS "Allow keepalive delete" ON "keep-alive";

-- 조회, 삽입, 삭제 정책 추가
CREATE POLICY "Allow keepalive select" ON "keep-alive"
    FOR SELECT TO anon, authenticated
    USING (true);

CREATE POLICY "Allow keepalive insert" ON "keep-alive"
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);

CREATE POLICY "Allow keepalive delete" ON "keep-alive"
    FOR DELETE TO anon, authenticated
    USING (true);
